<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccomodationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('accomodations')->insert([
            [
                'name' => 'Sunset Retreat Villa',
                'category_id' => 1,
                'photo' => 'sunset_retreat.jpg',
                'city_id' => 1,
                'address' => 'Jalan Serenity No.12',
                'health_protocol_fee' => 120000,
            ],
            [
                'name' => 'Ocean View Apartment',
                'category_id' => 2,
                'photo' => 'ocean_view_apartment.jpg',
                'city_id' => 2,
                'address' => 'Jalan Coastal No.75',
                'health_protocol_fee' => 180000,
            ],
            [
                'name' => 'Forest Haven Glamping',
                'category_id' => 3,
                'photo' => 'forest_haven_glamping.jpg',
                'city_id' => 3,
                'address' => 'Jalan Mountain Retreat No.300',
                'health_protocol_fee' => 220000,
            ],
            [
                'name' => 'Downtown Sky Hotel',
                'category_id' => 4,
                'photo' => 'downtown_sky_hotel.jpg',
                'city_id' => 4,
                'address' => 'Jalan Downtown Heights No.15',
                'health_protocol_fee' => 280000,
            ],
            [
                'name' => 'Mountain Lodge Villa',
                'category_id' => 1,
                'photo' => 'mountain_lodge_villa.jpg',
                'city_id' => 5,
                'address' => 'Jalan Nature Trail No.8',
                'health_protocol_fee' => 180000,
            ],
            [
                'name' => 'Serenity Apartment',
                'category_id' => 2,
                'photo' => 'serenity_apartment.jpg',
                'city_id' => 1,
                'address' => 'Jl. Tranquil Trees No.55',
                'health_protocol_fee' => 220000,
            ],
            [
                'name' => 'Riverside Glamping',
                'category_id' => 3,
                'photo' => 'riverside_glamping.jpg',
                'city_id' => 2,
                'address' => 'Jl. Riverbank No.11',
                'health_protocol_fee' => 1800000,
            ],
            [
                'name' => 'Enchanting Hotel',
                'category_id' => 4,
                'photo' => 'enchanting_hotel.jpg',
                'city_id' => 3,
                'address' => 'Jalan Enchanted Grove',
                'health_protocol_fee' => 210000,
            ],
            [
                'name' => 'Green Apple Villa',
                'category_id' => 1,
                'photo' => 'green_apple_villa.jpg',
                'city_id' => 4,
                'address' => 'Jalan Green Haven No.13',
                'health_protocol_fee' => 280000,
            ],
            [
                'name' => 'Peaceful Retreat Apartment',
                'category_id' => 2,
                'photo' => 'peaceful_retreat_apartment.jpg',
                'city_id' => 5,
                'address' => 'Jalan Peaceful Oasis No.14',
                'health_protocol_fee' => 180000,
            ],
            [
                'name' => 'Zen Glamping ',
                'category_id' => 3,
                'photo' => 'zen_glamping.jpg',
                'city_id' => 1,
                'address' => 'Jl. Zen Path No.47',
                'health_protocol_fee' => 220000,
            ],
            [
                'name' => 'Cityscape Hotel',
                'category_id' => 4,
                'photo' => 'cityscape_hotel.jpg',
                'city_id' => 2,
                'address' => 'Jl. Metropolitan No.9',
                'health_protocol_fee' => 1900000,
            ],
            [
                'name' => 'Tranquil Villa',
                'category_id' => 1,
                'photo' => 'tranquil_villa.jpg',
                'city_id' => 3,
                'address' => 'Jl. Tranquility Path No.23',
                'health_protocol_fee' => 1900000,
            ],
            [
                'name' => 'Bamboo Haven Apartment',
                'category_id' => 2,
                'photo' => 'bamboo_haven_apartment.jpg',
                'city_id' => 4,
                'address' => 'Jl. Bamboo Bliss No.32',
                'health_protocol_fee' => 1900000,
            ],
            [
                'name' => 'Orchid Glamping',
                'category_id' => 3,
                'photo' => 'orchid_glamping.jpg',
                'city_id' => 5,
                'address' => 'Jl. Orchid Oasis No.29',
                'health_protocol_fee' => 1900000,
            ],
            [
                'name' => 'Sunset Bliss Villa',
                'category_id' => 1,
                'photo' => 'sunset_bliss_villa.jpg',
                'city_id' => 1,
                'address' => 'Jalan Sunset Paradise No.12',
                'health_protocol_fee' => 120000,
            ],
            [
                'name' => 'Seaside Apartment',
                'category_id' => 2,
                'photo' => 'seaside_apartment.jpg',
                'city_id' => 2,
                'address' => 'Jalan Coastal View No.75',
                'health_protocol_fee' => 180000,
            ],
            [
                'name' => 'Magical Grove Glamping',
                'category_id' => 3,
                'photo' => 'magical_grove_glamping.jpg',
                'city_id' => 3,
                'address' => 'Jalan Enchanted Forest No.300',
                'health_protocol_fee' => 220000,
            ],
            [
                'name' => 'Cityscape Sky Apartments',
                'category_id' => 4,
                'photo' => 'cityscape_sky_apartments.jpg',
                'city_id' => 4,
                'address' => 'Jalan Urban Heights No.15',
                'health_protocol_fee' => 280000,
            ],
            [
                'name' => 'Mountain Escape Villa',
                'category_id' => 1,
                'photo' => 'mountain_escape_villa.jpg',
                'city_id' => 5,
                'address' => 'Jalan Nature\'s Peak No.8',
                'health_protocol_fee' => 180000,
            ],
            [
                'name' => 'Tranquil Oasis Glamping',
                'category_id' => 3,
                'photo' => 'tranquil_oasis_glamping.jpg',
                'city_id' => 1,
                'address' => 'Jalan Tranquility Path No.55',
                'health_protocol_fee' => 210000,
            ],
            [
                'name' => 'Riverside Paradise Villa',
                'category_id' => 1,
                'photo' => 'riverside_paradise_villa.jpg',
                'city_id' => 2,
                'address' => 'Jl. Riverside Haven No.11',
                'health_protocol_fee' => 1800000,
            ],
            [
                'name' => 'Enchanting Dreams Hotel',
                'category_id' => 4,
                'photo' => 'enchanting_dreams_hotel.jpg',
                'city_id' => 3,
                'address' => 'Jalan Enchanted Grove',
                'health_protocol_fee' => 210000,
            ],
            [
                'name' => 'Green Valley Hotel',
                'category_id' => 4,
                'photo' => 'green_valley_hotel.jpg',
                'city_id' => 4,
                'address' => 'Jalan Green Haven No.13',
                'health_protocol_fee' => 280000,
            ],
            [
                'name' => 'Peaceful Haven Villa',
                'category_id' => 1,
                'photo' => 'peaceful_haven_villa.jpg',
                'city_id' => 5,
                'address' => 'Jalan Peaceful Oasis No.14',
                'health_protocol_fee' => 180000,
            ],
            [
                'name' => 'Coastal Retreat Hotel',
                'category_id' => 4,
                'photo' => 'coastal_retreat_hotel.jpg',
                'city_id' => 2,
                'address' => 'Jalan Coastal Escape No.75',
                'health_protocol_fee' => 180000,
            ],
            [
                'name' => 'Tranquil Oasis Apartment',
                'category_id' => 2,
                'photo' => 'tranquil_oasis_apartment.jpg',
                'city_id' => 3,
                'address' => 'Jalan Tranquil Haven No.300',
                'health_protocol_fee' => 220000,
            ],
            [
                'name' => 'Urban Escape Villa',
                'category_id' => 1,
                'photo' => 'urban_escape_villa.jpg',
                'city_id' => 4,
                'address' => 'Jalan Urban Heights No.15',
                'health_protocol_fee' => 280000,
            ],
            [
                'name' => 'Mountain Serenity Hotel',
                'category_id' => 4,
                'photo' => 'mountain_serenity_hotel.jpg',
                'city_id' => 5,
                'address' => 'Jalan Nature\'s Peak No.8',
                'health_protocol_fee' => 180000,
            ],
            [
                'name' => 'Enchanted Glade Glamping',
                'category_id' => 3,
                'photo' => 'enchanted_glade_glamping.jpg',
                'city_id' => 1,
                'address' => 'Jalan Enchanted Grove No.55',
                'health_protocol_fee' => 220000,
            ],
            [
                'name' => 'Riverside Tranquility Hotel',
                'category_id' => 4,
                'photo' => 'riverside_tranquility_hotel.jpg',
                'city_id' => 2,
                'address' => 'Jl. Riverside Haven No.11',
                'health_protocol_fee' => 1800000,
            ],
            [
                'name' => 'Harmony Haven Glamping',
                'category_id' => 3,
                'photo' => 'harmony_haven_glamping.jpg',
                'city_id' => 3,
                'address' => 'Jalan Harmony Retreat',
                'health_protocol_fee' => 210000,
            ],
            [
                'name' => 'Green Meadows Hotel',
                'category_id' => 4,
                'photo' => 'green_meadows_hotel.jpg',
                'city_id' => 4,
                'address' => 'Jalan Green Oasis No.13',
                'health_protocol_fee' => 280000,
            ],
            [
                'name' => 'Peaceful Pines Villa',
                'category_id' => 1,
                'photo' => 'peaceful_pines_villa.jpg',
                'city_id' => 5,
                'address' => 'Jalan Peaceful Path No.14',
                'health_protocol_fee' => 180000,
            ],
            [
                'name' => 'Sunset Ridge Apartment',
                'category_id' => 2,
                'photo' => 'sunset_ridge_apartment.jpg',
                'city_id' => 1,
                'address' => 'Jalan Ridge View No.47',
                'health_protocol_fee' => 1900000,
            ],
            [
                'name' => 'Serenity Glamping',
                'category_id' => 3,
                'photo' => 'serenity_glamping.jpg',
                'city_id' => 3,
                'address' => 'Jl. Tranquility Path No.23',
                'health_protocol_fee' => 1900000,
            ],
        ]);
    }
}